Add basic react project setup, linter configs, & react-router
MuhammadUsmanAslam/bookstore pull request #1
Opened 2023-03-29 20:48 UTC by MuhammadUsmanAslam

The following changes are being suggested to merge:

- Add 2 routes in your application:
- - `/ , which contains
- - - A book list, where each book has a title and author
- - - A form that allows for creating a new book
- - `/categories`
- - - This should display a button that checks for a status
- Include a navigation component that includes links to the 2 routes you created

2023-03-29 21:36 UTC, mwanawabangona requested changes
Hi @MuhammadUsmanAslam ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that `does not have a descriptive readme file`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-29 21:36 UTC, mwanawabangona commented on README.md
> +See the section about [deployment](https://facebook.github.io/create-react-app/docs/deployment) for more information.
- [ ] `Required`
- [ ] Please add a more descriptive `Readmefile` 
- [ ] pleaase follow this [README template](https://github.com/microverseinc/readme-template)

2023-03-30 09:07 UTC, omarsalem7 requested changes
Hi @MuhammadUsmanAslam 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/j7vckgz15cAYmxatzB/giphy.gif)

## Highlights
- Use React Router. ✔️
- The Pull Request has a proper title and description. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 09:07 UTC, omarsalem7 commented on src/components/Home/Home.js
> +    </div>
- [x] It will be better to divide this component into sub-components to make your code reusable and clean by creating
- `<BookList>` component to render a list of books using the <Book> component
           - `<Book>` component which takes the book data as a prop and renders the title and the author and has a button for removing the book

- `<NewBookForm>` component to render a form with inputs for the title and the author of the book

2023-03-30 11:08 UTC, Owusu-Desmond approved these changes
Hi @MuhammadUsmanAslam , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 12:27 UTC, merged